name: Run tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: $HOME/SpacemanDMM
          key: ${{ runner.os }}-spacemandmm
      - name: Install Build Tools
        run: |
          bash tools/ci/install_spaceman_dmm.sh dreamchecker
          pip3 install setuptools
          pip3 install -r tools/mapmerge2/requirements.txt
      - name: Run Linters
        run: |
          tools/ci/check_filedirs.sh tgstation.dme
          tools/ci/check_changelogs.sh
          find . -name "*.php" -print0 | xargs -0 -n1 php -l
          find . -name "*.json" -not -path "*/node_modules/*" -print0 | xargs -0 python3 ./tools/json_verifier.py
          tools/ci/build_tgui.sh
          tools/ci/check_grep.sh
          python3 tools/mapmerge2/dmi.py --test
          ~/dreamchecker
